services:
  abios-relay:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file: .env
      

  redis:
    image: redis:7
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password
